-- Table: ncs.columnmap

-- DROP TABLE IF EXISTS ncs.columnmap;

CREATE TABLE IF NOT EXISTS ncs.columnmap
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    provider text COLLATE pg_catalog."default" NOT NULL,
    target text COLLATE pg_catalog."default" NOT NULL,
    pname text COLLATE pg_catalog."default" NOT NULL,
    tname text COLLATE pg_catalog."default" NOT NULL,
    popt jsonb,
    sync boolean NOT NULL,
    tenant text COLLATE pg_catalog."default",
    CONSTRAINT columnmap_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ncs.columnmap
    OWNER to postgres;

-- Table: ncs.idmap

-- DROP TABLE IF EXISTS ncs.idmap;

CREATE TABLE IF NOT EXISTS ncs.idmap
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    provider text COLLATE pg_catalog."default" NOT NULL,
    target text COLLATE pg_catalog."default" NOT NULL,
    pid text COLLATE pg_catalog."default",
    tid text COLLATE pg_catalog."default",
    targetlist text[] COLLATE pg_catalog."default",
    targetstatus text COLLATE pg_catalog."default",
    targetvalue jsonb,
    tenant text COLLATE pg_catalog."default",
    mergedvalue jsonb,
    option jsonb,
    CONSTRAINT idx_id PRIMARY KEY (id),
    CONSTRAINT idmap_provider_target_pid_key UNIQUE (provider, target, pid),
    CONSTRAINT idmap_provider_target_pid_tenant_key UNIQUE (provider, target, pid, tenant)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ncs.idmap
    OWNER to postgres;

-- Table: ncs.session

-- DROP TABLE IF EXISTS ncs.session;

CREATE TABLE IF NOT EXISTS ncs.session
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    apisignature text COLLATE pg_catalog."default" NOT NULL,
    sessionid text COLLATE pg_catalog."default" NOT NULL,
    accessdate timestamp without time zone NOT NULL,
    tenant text COLLATE pg_catalog."default",
    "from" bigint,
    CONSTRAINT session_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS ncs.session
    OWNER to postgres;
